### ISSUE TITLE
Please consider displaying Google/Facebook avatar

### ISSUE THREAD

**Issue by morphinestyle** [akeeba/sociallogin#105]
Hello Nicholas.
Can you consider the possibility of displaying the Google or Facebook avatar with a short code? (rendering the image or rendering even just the Google/Facebook avatar URL)
Or store the avatar URL in the database in the _user_profiles table so anyone can use it?

The ideal would be a separate plugin to add to Social Login where you can manage the priority between the presence of multiple avatars from different integrations.

**Comment by nikosdion** [comment]
Not all services will give us an avatar URL. This means that SocialLogin itself could never be a generic solution for providing avatars as there is no fallback, nor can there be a fallback (not without overreaching beyond the scope of the software).

To avoid  this situation we would need to have SocialLogin merely act as an avatar _provider_ to a centralised avatar display feature in Joomla! itself. 

Joomla does not have such a feature (though, if you ask me, it _should_). Coming up with our own avatar solution is pointless because it would require other Joomla software to adopt it, and template overrides for everything that doesn't. This has been tried too many times before, and none of these solutions was adopted beyond the company which came up with them. So, us trying to follow the same failed path? Well, I can best reply with an [obligatory XKCD](https://xkcd.com/927/).

That's why I decided against trying to provide an avatar with SocialLogin. We have the code to collect the avatar URLs. If Joomla ever comes up with a centralised avatar API we will be more than happy to write the little bit of code required to make SocialLogin a provider of avatars to this API. I could have even proposed such an API —it's ridiculously simple— but they've blocked me off Joomla's GitHub therefore I cannot do that. Moreover, the Joomla core maintainers have long stopped being in touch with the community and have alienated all 3PDs, therefore I don't think you will ever see them implementing something like that or accepting a contribution to that effect either.

What I have resorted to is using Gravatar on my sites and software, giving people the dead simple instructions necessary to create or edit it. It does the job just fine.
