### ISSUE TITLE
buttons icon feature - icon font

### ISSUE THREAD

**Issue by mino182** [akeeba/sociallogin#109]
**Is your feature request related to a problem? Please describe.**
I would like to ask if you are considering using the `$button['icon']` value in your buttons? I see it in core login module, but no "extra button" in  Joomla uses it. Every extra login buttons (core and SocialLogin) uses only SVG. But SVGs are complicate to style and make them looking matching each other...

**Describe the solution you'd like**
It will be great to have a field in button plugin, for insert own icon classes, but standard FA classes for joomla default fontawesome 5 (e.g. fab fa-facebook) will be also great.

**Why do you think this is relevant to people other than you**
I think this would be a good option for everyone who wants to use multiple buttons and wants them to "visually matching". Also icon fonts are easier to style.

**Additional context**
Maybe there is reasons for using SVG with no change option, if so, could you please write why?

Thank you.

**Comment by nikosdion** [comment]
Joomla!, before version 4.0, did not have an additional login buttons feature. I contributed this feature in March 2020 as part of the Login with WebAuthn feature. 

The additional login buttons feature I contributed to Joomla! was modelled after what I was already doing with SocialLogin. It was, indeed, using an icon, not an SVG files.

For reasons unrelated to me and my contribution, the Joomla! project decided to move from using icons to using SVG files. Since no core code was using icons anymore, they have no good styling for icons, and third party templates also don't support icons at all.

Therefore, I had to change SocialLogin, moving from icons to SVG files.

I fully understand what you mean about styling. They can still be styled, but SVGs can be quite a pain in that regard. Since Joomla! does not want to support icons, I can't either. Sorry. It was absolutely not my choice.
