### ISSUE TITLE
Utilizing CB 'First Login Redirect' feature with Akeeba Social Login

### ISSUE THREAD

**Issue by Pakeydev** [akeeba/sociallogin#111]
I would be grateful if you could guide me on how to effectively use the 'First Login Redirect' feature while employing Akeeba Social Login with Community Builder.

I have successfully set it up, however, I am encountering difficulties as the 'First Login Redirect' feature does not seem to function as expected with Akeeba Social Login. It doesn't redirect to the link we provide.

Could you kindly provide guidance on the appropriate settings?

Thank you.

Fresh install of Joomla 5.0.1, default template.
SocialLogin 4.7.1
CB 2.9.1
PHP Version 8.2.13

**Comment by nikosdion** [comment]
It is unlikely that this kind of feature will work with SocialLogin.

In the regular Joomla! user registration flow you have discrete pages for account creation, account activation, and account login. In the latter page you have a redirection to a URL set up by a URL parameter.

Using SocialLogin the user registration, activation, and login happen at the same time. The redirection is performed against a URL stored in the user session.

SocialLogin cannot be modified to work like Joomla's user registration. That's the whole point of SocialLogin: remove the friction from user registration. You can of course tell SocialLogin to not allow for user registration, but that kinda beats the purpose. Your users would need to create a user account the “regular” way (register, activate, log in), then edit their user account to enable logging in with a social network account. That would completely beat the purpose.

CommunityBuilder would need to add specific support for SocialLogin for their feature to work. Since they are unlikely to do that, I am saying that this CommunityBuilder feature is unlikely to work.
