### ISSUE TITLE
Click 'Cancel' button give an error

### ISSUE THREAD

**Issue by Pakeydev** [akeeba/sociallogin#124]
Steps to reproduce the issue
Browser have multiple Google account logged in. Go to website and Click Google Sign In button, on the 'Choose an account' choose which Google account to sign in with, at the 'Sign in to...' page, click the 'Cancel' button.

![image](https://github.com/user-attachments/assets/e13d6a3a-7ec5-4d99-b5c1-c7bee157d769)

![image](https://github.com/user-attachments/assets/21d33b62-b388-458d-a66a-0254b6699e85)

Expected result

Go back to website with a Google Sign button

Actual result

Give an error Akeeba\Plugin\Sociallogin\Google\Extension\Plugin::getSocialNetworkProfileInformation(): Return value must be of type array, bool returned0/home/mysite/public_html/plugins/sociallogin/google/src/Extension/Plugin.php129Array

In Error Log;
PHP Warning:  Array to string conversion in /home/mysite/public_html/components/com_ajax/ajax.php on line 230

System information

Mandatory information
SocialLogin 4.8.2
Joomla! version: 5.2.1
PHP version: 8.2.24
Am I using HTTPS: Yes
Server Operating System: Linux
My device's Operating System: Windows
My device's Operating System version: Windows 11
Browser: Chrome
Browser version: Version 130.0.6723.117

**Comment by nikosdion** [comment]
We do not have any kind of control over what _Google itself_ does. Your request to go back to selecting a different account when you click Cancel on _Google's interface_ is obviously and objectively something outside our control since, well, we are not Google. Besides, what you are asking for is already implemented by Google, using the drop-down you see on the left-hand side of your screenshot.

When you click on Cancel on Google's authorization interface you are effectively telling Google to reject the authorization requested by your site. An error is to be expected in this case. We can improve the error a little bit, but the fact remains that in this case you should expect to receive an error since you have explicitly denied authorizing the site to access the basic information of your Google account.

**Comment by Pakeydev** [comment]
I didn’t request anything; I’m just informing you and reporting what I’ve found to help improve your plugin. Also, I didn’t ask for it to revert to selecting an account; I assumed it would go back to our website, not Google’s account selection page. I’m not familiar with Google’s implementations because I’m not a coder. I’m simply trying to help, so if you don’t appreciate it, just ignore it. There’s no need to be arrogant.

**Comment by nikosdion** [comment]
I was replying to this:

> Go back to website with a Google Sign button

I replied with simple facts, to what I understood you asked from a very circumspect and vague sentence. I was being factual. If there was a misunderstanding you could let me know, politely. Instead, your reaction to your _assumption_ of what motivated my reply was to call me names. Wow.

Well, you're welcome for addressing this issue on a Sunday for the free of charge software I've been publishing for years.
