### ISSUE TITLE
Creating users on authentication not functioning.

### ISSUE THREAD

**Issue by phooka** [akeeba/sociallogin#13]
First, I get it that it's not even Alpha, but I thought I'd throw this out.

I have installed and setup this package (awesome by the way thanks!) but am having a problem with getting accounts created.  It just doesn't seem to work.  I've enabled registrations, and self-activation, I've also set the plug-in to ignore Joomla settings for creating accounts.  When I login via Facebook I get the following:

Warning
You do not have an account on this site that corresponds to this Facebook account.

Note, the same issue seems to occur with Google authentication as well.

Warning
You do not have an account on this site that corresponds to this Google account.

**Comment by phooka** [comment]
I'm partly there.  In handleSocialLogin() the PHP function empty($userData->email) was returning true.  I created a new variable in the function called $userEmail and assigned it the value of $userData->email.  It worked, and created a new user.  Now I'm getting "You can't access the private section of this site."  

I'm somewhat getting there.

**Comment by nikosdion** [comment]
Fixed with commit ef165ed687c0d3b0da94d135a22cbaf398f7bfa6

The second message means that you haven't -yet- validated the new user account. Remember that Social Login follows your Joomla! settings, as set up in the Users page's Options. If you haven't touched the default settings you are sent an email to verify your account.

Also note that the default User Group the new user is assigned to is also defined in the same Options page. If you have chosen a User Group which doesn't have the Login privilege (as set up in Joomla's Global Configuration) you will not be able to log in, hence the error message.
