### ISSUE TITLE
Social login buttons apear on admin login page also

### ISSUE THREAD

**Issue by Cyrusxxx** [akeeba/sociallogin#16]
### Steps to reproduce the issue
Install plugin and enable it
Disable auto insert buttons function
Insert code in template override for login module mod_login/ default.php
`<?php if (class_exists('SocialLoginHelperIntegrations')) echo SocialLoginHelperIntegrations::getSocialLoginButtons() ?>` 

Button is displayed properly on frontend in module

### Expected result
Social login button should be displayed only on front end of Joomla 

### Actual result
Social login button is displayed on frontend and in login module for administrators
Check screenshot:
https://prnt.sc/glb839

### System information (as much as possible)
* **Joomla! version**: 3.7.5
* **Database type**: MySQL
* **Database version**: 5.x
* **Server type**: Apache
* **Server version**: x.y.z
* **Hosting company / Local server**:Hostgator

* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux,
* **Server Operating System version**: e.g. Windows 10, Ubuntu 16.04, ... Type N/A if it's a live host and you have no idea. 
* **Browser**: Chrome, Firefox, Edge, Internet Explorer, Safari, Opera,
* **Browser version**:60

**Comment by nikosdion** [comment]
So, this is a bug and a non-bug at the same time 😃 

SocialLogin allows you to use it for back-end login. It does so even if you do not create template overrides for the back-end. As documented, when there are no overrides we just inject the buttons at the end of the module which works well enough for the core modules and core templates (by definition what is used in the backend login page). So that part isn't a bug.

However, the default behavior should be that the backend login buttons are NOT present unless you explicitly set it up. There was an unfortunate default of `mod_login` being used when the field is empty which is what caused this issue. That is a bug and I fixed it.

Meanwhile, if you do not want to display the SocialLogin buttons in the backend please edit the options for the System - SocialLogin plugin. The second option, with the broken label, is the list of backend modules. Set it to `none` and click on Save & Close. Now you will no longer see those pesky buttons in the backend login page :)

**Comment by Cyrusxxx** [comment]
Thank you for this explanation and solution mr. Dionysopoulos yes it has solved my small issue so to speak.
Btw, I have intended to send you mail and express my gratitude to you for developing this plugin but this is even better.
It is kinda funny story how it all started...
 On my site which I am about to launch I use Kunena and JomSocial and JomSocial is used for registrations etc. But since JS has only facebook integration available for registration and login, I have installed first Ajax Improved Login and register component and then all problems have started... 
Than I have switched to JFBConnect component and yes it was vorking but OMG so much editing to adjust it to look good and it is kinda heavy component because all I wanted were 3 simple buttons.
After realizing that it is not up to my taste to use JFBConnect I came with idea!
Why not use JomSocial facebook login code and implement it to joomla login modules and pages and since redirection is set properly when clicked on button JomSocial would take over... But no!!! that was impossible.
And then I have started searching and stumbled upon your **great plugin**. Few copy-paste in plugin and few copy-paste in code, little css magic and **Voila**!  All done! Plugin is not heavy for system, no errors, can place codes anywhere I want, reputable developer and simply perfect.

So thank you again for developing this plugin mr. Dionysopoulos and if there is a way I can contribute please let me know or at least make donation or something. 
Thank you again.

With kind regards, Goran Nešić.

**Comment by nikosdion** [comment]
You're welcome, Goran! I am glad I could make your life a little bit easier :)

**Comment by gerrypidecssgithub** [comment]
> Meanwhile, if you do not want to display the SocialLogin buttons in the backend please edit the options for the System - SocialLogin plugin. The second option, with the broken label, is the list of backend modules. Set it to `none` and click on Save & Close. Now you will no longer see those pesky buttons in the backend login page :)

Hello, 
and how does the deactivation of the social login buttons in the backend for Joomla 4 (4.4.1) work? 
I can't find an option for it in the system - SocialLogin plugin. 

Many thanks in advance,
Gerry

**Comment by nikosdion** [comment]
@gerrypidecssgithub Please do not comment on **unrelated** issues from six years ago. This issue was talking about Joomla! 3. You are asking about Joomla! 4. The way SocialLogin works in each Joomla! major version has absolutely nothing to do. Joomla! 3 had no provision for additional login buttons, therefore we had to implement our own code. Joomla! 4 has, since 4.0, native support for additional login buttons which is exactly what we now use.

Since SocialLogin buttons are standard Joomla! login button plugins they will be displayed by any front- or backend component and module which renders a login page. If you want to disable **ALL** login button plugins – including WebAuthn / Passkey login – you can make a template override for the backend mod_login module.
