### ISSUE TITLE
2 Ideas

### ISSUE THREAD

**Issue by Cyrusxxx** [akeeba/sociallogin#18]
It would be nice to have injection code to chose what social buttons to display.
For example on one module I have need for 3 social login buttons, but on other module/place I need for example displayed only two buttons.

Second one is when user is registered or logged in for plugin to pull avatar from that social network.

Thank you!

**Comment by nikosdion** [comment]
>  For example on one module I have need for 3 social login buttons, but on other module/place I need for example displayed only two buttons.

This will not be implemented. SocialLogin is a set of plugins. If the plugin is published and its access control indicates that it's available for the current user then `SocialLoginHelperIntegrations::getSocialLoginButtons()` returns all of the login buttons. It doesn't render these buttons itself; each plugin is responsible for rendering its own buttons. Since it goes through the Joomla! events dispatcher which comes with a performance cost it caches the results. So no matter where you call it from it will always return the same list. Doing anything else would be both over-complicated and a performance nightmare.

You can always copy the code of `SocialLoginHelperIntegrations::getSocialLoginButtons()` into your template overrides and filter out `$buttonDefinition` records inside the `foreach()` loop with your custom criteria. However, this is well beyond the scope of what SocialLogin is designed to provide.

Finally, it is disastrously bad UX if you do not have a constant offering of social login methods across your site. If I register an account to your site through Facebook I might not even be aware of my username and randomized password (since they were sent to me by an email which ended up in my spam but I was already logged into your site so who cares?). If I visit your site a week later, through another landing page, with another login module that lacks Facebook authentication I will think that your site is broken. Most likely I will leave in frustration.

> Second one is when user is registered or logged in for plugin to pull avatar from that social network.

Um, no. This set of plugins is called SocialLogin, not SocialAvatar ;) Social avatars are to social logins what a car wash is to a car repair shop.

In more practical terms, there is no single Joomla! avatar API used by every extension out there. On the contrary, every extension has its own API. So you are asking me to write a dozen plugins _for each social network_. Each one of these plugins would require extensive testing against different Joomla!, PHP and third party extension versions (and their combinations). Expecting me to do that -even for a fee- is very unrealistic, I'm afraid.

To put things in perspective, all of _our_ software use the same avatars API. We considered adding Facebook and Twitter account support but we decided not to because it was a massive pain in the rear. That includes at least one component we sell subscriptions for (Akeeba Ticket System). We figured out that there was no return of the substantial time investment - social avatar integrations need to be rewritten periodically as social networks change their APIs. As you understand there's no way I can do that across multiple third party APIs and for free :)
