### ISSUE TITLE
Limite access with Google to special domain/s

### ISSUE THREAD

**Issue by klabog** [akeeba/sociallogin#19]
First, my congratulations for this great idea! The ancient social login in the Joomla Extensions is long ago obsolete and as far as I have ascertained so far, all other attempts are not really impressive.
1) Could you develop an option, which allows the access via Google only for one / several domain/s?
2) At least an option would be helpful, which allows one or more domains to access defined user groups.
We are a non-profit organisation and have Google Suite in use. It would be practical if all members could get directly into the appropriate user group and guests would only have access to the public area.
I believe that this feature could be useful to many Google Suite users.
3) Similarly, access to other user groups via other social networks could result interesting.
Greetings, Klaus

**Comment by nikosdion** [comment]
> Could you develop an option, which allows the access via Google only for one / several domain/s?

No. Google does not give you such an option. Technically, it's Google Plus login (that's what the API says). 

Even though I can think of roundabout ways to achieve a similar effect (inspect the email address of the user being logged in) it sounds more like a hack. I don't even know if the assumption that all Google Suite accounts will have email addresses in the company's domain name (e.g. `@example.com`) is true and also applies in reverse (all `@example.com` email addresses are Google Suite accounts for that company). I also don't know how that works with existing Google+ profiles and adding multiple email addresses to them. 

Since I have no way to test any of these assumptions in a *determinant manner* I am more than reluctant on implementing a feature which is likely to be broken. Also, based on your other points it sounds like it would be useless for your prupose.

> At least an option would be helpful, which allows one or more domains to access defined user groups.

This should be best implemented with a custom `user` plugin. The plugin would hook at the `onUserBeforeSave` event (see the [profile plugin](https://github.com/joomla/joomla-cms/blob/staging/plugins/user/profile/profile.php#L360) for an example) and assign privileges based on the user's email address but *only* when the second argument, `$isnew`, is true. This way you auto-assign privileges based on a (verified) email address only when someone creates a user account.

Since you would have such a custom user plugin you can always add custom validation logic for determining when someone is a member of your organization. When you determine they are not you can throw an `InvalidArgumentException` with an error message. The user would see the error message and no user record would be created in Joomla!. As a result you are now in absolute, programmatic control of user registration.

Please note that such a plugin is out of scope of SocialLogin. However, this is a trivial task that even a cheap outsourced developer could do in less than an hour. The hard part was thinking of how to implement this elegantly which I did for you already ;)

> Similarly, access to other user groups via other social networks could result interesting.

Covered by the custom plugin approach above. Being a user plugin it's a universal solution. It doesn't matter how the user registers: SocialLogin, Joomla's com_users (user registration form), a third party extension etc.

**Comment by klabog** [comment]
Thank you for your quick response. Ok, will try a custom plugin.
Just installed your social access and configured Google Plugin. It seems not to work.
Perhaps it's because I don't have a normal login. I do it with an hidden directory. Better: I did it tow years ago and now I have to figure out how I did it :-(
The Google part is OK. 
[https://ateneomotril.org](url)
You enter on "Mi Cuenta". This leads to a page where you have to login and therefore opens the login dialog.
I noticed that there is missed a translation : PLG_SYSTEM_SOCIALLOGIN_CONFIG_BACKENDLOGINMODULES_LABEL
It's not present in english too.

**Comment by nikosdion** [comment]
Sorry, we do not provide end user support. Please follow the setup instructions [in the Wiki](https://github.com/akeeba/sociallogin/wiki). You need to enable and configure BOTH the system plugin AND the specific login plugin. Do read the section about the necessary configuration with template overrides, especially if you are not using the core Joomla! components for logging in users.
