### ISSUE TITLE
Google Plugin doesn't work as supposed

### ISSUE THREAD

**Issue by klabog** [akeeba/sociallogin#21]
### Steps to reproduce the issue
1) Install social login packet on your site (I used a clean demo.site)
2) Configure social login system plugin (only entered in the second line: none - had to figure out what is expected there because the language-tag has no text defined)
3a) Configure and publish google plugin with your correct credentials of Google
3b) Put all five options to Yes
4) Publish a login form (Google Login is visible)
5) Login with Google Login
### Expected result
User should be created under all circumstances without e-mail confirmation and login should be possible
### Actual result
1) User is created but not enabled nor activated
2) Admin gets mail New User Inscription
3) User gets mail to confirm new account 
### System information (as much as possible)
PHP Built On | Linux jm101.siteground.biz 2.6.32-642.6.2.el6.x86_64 #1 SMP Wed Oct 26 06:52:09 UTC 2016 x86_64
Database Version | 5.5.39-36.0-log
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.0.23
Web Server | Apache
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.8.0 Stable [ Amani ] 19-September-2017 14:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36
* **Am I using HTTPS**: No
* **Browser**: Chrome.
* **Browser version**: 61.0.3163.100 (Offizieller Build) unknown (64-Bit)
### Additional comments
When "Ignore Joomla! setting for creating user accounts" is set to NO I'm getting an error (see added screenshot)
![bildschirmfoto vom 2017-09-27 21-02-45](https://user-images.githubusercontent.com/6863300/30932303-65b7a890-a3c7-11e7-9973-15be19646ad0.png)
![bildschirmfoto vom 2017-09-27 20-32-08](https://user-images.githubusercontent.com/6863300/30932304-65cc08b2-a3c7-11e7-9ad3-5376457115c1.png)
![bildschirmfoto vom 2017-09-27 20-04-53](https://user-images.githubusercontent.com/6863300/30932305-65d680c6-a3c7-11e7-8f2c-62d5bf7b550a.png)
I'm understanding that "Bypass user verification" should do what it says: Bypass user verification, but it doesn't.
![bypass](https://user-images.githubusercontent.com/6863300/31045162-b1d22a58-a5dd-11e7-9b80-e7310479de0d.png)

**Comment by nikosdion** [comment]
In order to allow users to register without an email being sent in your scenario you will need two conditions to be BOTH true at the same time.

**Condition 1: Correct configuration of the plugin** (satisfied per your screenshot)

All of the following options must be set to Yes in the plugin:
* Allow social login to non-linked accounts
* Create new user accounts
* Ignore Joomla! setting for creating user accounts
* Bypass user validation

**Condition 2: Correct account validation status returned by Google**

Google returns a list of emails linked to your profile. If there is an email address with the metadata type=account then and only then we consider the email pre-validated by Google. In this and only this case will we suppress the email to validate the user's email address. If this field is not returned for any reason we have no reason to believe that Google has verified the user's identity, therefore we cannot bypass Joomla!'s email verification checks.

This issue seems to depend on the data returned by an opaque, third party API (Google+). All we can do is check that our code conforms to their API documentation, which it does. Therefore I am closing this issue as invalid.
