### ISSUE TITLE
Unable to log in with Twitter account 

### ISSUE THREAD

**Issue by Sulpher** [akeeba/sociallogin#25]
### Steps to reproduce the issue
I've created a Twitter dev account and added keys to the plugin settings according to the tutorial.
I have accounts on FB, Twitter and G+ registered on the same e-mail.

### Expected result
Successful login. 

### Actual result
I can log in to the site using FB and G+ without a problem (my e-mail is the same on both accounts). 
When I am attempting to log in using Twitter, I get the following error:

**You do not have an account on this site that corresponds to this Twitter account.**

### System information (as much as possible)
* **Joomla! version**: 3.8.2
* **PHP Version**: 7.0.23
* **Database type**: MySQL
* **Database version**: 5.5.52-MariaDB
* **Am I using HTTPS**: Yes
Social Login version 1.0.2

### Additional comments
I've played with settings and tried to enable and disable them all, but the effect is the same: I am not able to sign in to the site.
![screen shot 2017-11-13 at 16 25 46](https://user-images.githubusercontent.com/3432048/32728036-dd63e8c6-c88f-11e7-8913-ef3669727550.png)

**Comment by nikosdion** [comment]
You have set "Allow social login to non-linked accounts" to No. This means that you need to link your Joomla! user account with your Twitter account _before_ trying to log in using Twitter. To do so, login to your user account from the frontend of your site, go to your Joomla! user profile, edit, Link Twitter, log out and then try to log back in. 

Alternatively you can enable the "Allow social login to non-linked accounts" (set it to Yes). In this case you do not have to link your Joomla! user account with your Twitter account. You just need to make sure that they both use the same email address.

**Comment by Sulpher** [comment]
@nikosdion I am sorry, but setting **Allow social login to non-linked accounts** to **Yes** does not make a required effect and I get a warning message when attempting to log in with a Twitter account. 
A video can be better instead words.
Please watch this short video:
https://www.dropbox.com/s/1gxtluqoe20k32f/social-login.mp4?dl=0

**Comment by nikosdion** [comment]
I have to insist that the problem is that the email you have on Twitter is EITHER not verified OR is not 100% the same as the one you are using on your site. The following emails are different as far as SocialLogin is concerned:

Foo.Bar@example.com
foo.bar@example.com
foo.bar@Example.com
FOO.BAR@EXAMPLE.COM
foo.bar+something@example.com

The email you use on Twitter.com must match character for character the one you use with Joomla!, including the exact capitalization. This is intentional. When you deal with UTF domains the capitalization in some languages does matter. The user part of the email (left hand side before the @ sign) may be case sensitive in some systems. The plus sign may also either be part of the username or, like with Google Mail, denote a disposable suffix. Since these are all unknowns the only reasonable thing to do is compare the email addresses as literal strings. 

Please note that I tested that this feature works as it should before replying to you on my own sites. 

As for the missing icons please refer to the documentation. It explains why it might happen and what to do (hint: template overrides).

**Comment by nikosdion** [comment]
No, you don't have to be a verified _user_, just have your email verified by Twitter. Verified users is something that Twitter has stopped doing anyway (you won't see any more people getting the blue checkmark in the foreseeable future).

Anyway, this is strange because I'm trying the same thing on my site and it works. I think you have a configuration issue. Let's take this step by step.

In the Joomla site you have an account with email user@example.com. The user is *NOT* linked with any Twitter account.

On Twitter you have an account with email user@example.com. This Twitter account is *NOT* linked with any user on your Joomla! site.

You have enabled "Allow social login to non-linked accounts" in the Twitter plugin. **In your screenshot this was DISABLED!**

If you try to log in with Twitter you will end up being logged in with the Joomla! user account that matches the user@example.com .

Please note that:
* if any of these conditions are not met you will not log into the site.
* the code which logs you into the site is actually common and part of the system plugin. That is to say, it's impossible that it works with Facebook but not with Twitter. All social login plugins pass a social network user ID and the email address reported by the social network to the system plugin which then tries to log you in.

**Comment by b2z** [comment]
@nikosdion I have exactly the same message testing. Login ok via FB & G+ and fails via Twitter :(

**Comment by Sulpher** [comment]
@nikosdion 

> You have enabled "Allow social login to non-linked accounts" in the Twitter plugin. In your screenshot this was DISABLED!

I tried to enable/disable each param and checked out logging via Twitter.
That's very strange. I try once again and will record another video.

**Comment by nikosdion** [comment]
So, it seems that the problem comes from Twitter's end.

When I try using a Twitter App I had _already_ created months ago, the Twitter API returns the email address of the user. Therefore I can look up the Joomla! user by email address and log you in.

Today I tried creating a *new* Twitter app. In this case the Twitter API did NOT return the user's email address! As a result I cannot find an existing user. So, I throw an error about no such user found.

Sorry, guys, This seems unfixable. If Twitter won't return the email address of the user then the only thing we can do is require that the users have already linked their Twitter account before trying to log in.

**Comment by nikosdion** [comment]
Dammit, I must have been half asleep! Actually, Twitter [does document](https://developer.twitter.com/en/docs/accounts-and-users/manage-account-settings/api-reference/get-account-verify_credentials) that *by default* they will not send you the user's email address _UNLESS_ you tick the "Request email addresses from users” checkbox which is available under the app permissions on apps.twitter.com. However, if you want to do that, you MUST fill in the Privacy Policy URL and Terms of Service URL fields *BEFORE* Twitter shows you this checkbox.

So, all of our tests were correct, guys. My existing site was using a Twitter app that had this permissions, hence it was receiving the email of the user and worked perfectly. My new app and your apps do not have this permissions which is why they don't work.

I am going to leave this closed and improve the documentation.

**Comment by nikosdion** [comment]
I have updated [the documentation](https://github.com/akeeba/sociallogin/wiki/Twitter) with the counter-intuitive steps you have to follow on Twitter's site to enable transmission of the all important email address. Please test these instructions and let me know if that worked for both of you :)

**Comment by Sulpher** [comment]
Hi @nikosdion I have been played with dev site using your recommendations and all is just fine! I can register on the site via Twitter. Thank you very much for solving this question! You are the champion! :-)

Just one question: I tried to enable and disable **Bypass user validation** param in all plugins (FB, G+ and Twitter), but the result is the same - the system sends a notification at e-mail with an activation link. As far as I understood, this option should enable or disable such kind of checking. 

Step-by-step actions:
I enable Bypass user validation param and get activation URL at the e-mail if the user does not exist. I remove this non-active user to reproduce this action again. Then I go back to the plugin settings and disable Bypass user validation param. After logging in I get the same activation URL anyway. 
I suppose, there should be automatic user activation without confirming via e-mail...

**Comment by nikosdion** [comment]
Can you please file a different issue for this? Otherwise it's impossible for either of us to keep track.

**Comment by skyemans** [comment]
Hi @nikosdion ,
I am trying to get the Social login set up on my Joomla site. Google plugin works fine, but Facebook gives message _"You do not have an account on this site that corresponds to this Facebook account."_ , even when it is configured to create new accounts.

I have tried the demo (https://myoldsite.com/) and it's the same, so it must be the plugin itself.
Any ideas?
Cheers

**Comment by nikosdion** [comment]
It's already fixed in the current code base. No, there is no release just yet.

FYI, it's caused by a Facebook API change. After their disastrous year they cut off applications' access to several profile fields including the `verified` one. Now the only Facebook accounts reported by the API are those with a verified email address, meaning this field is no longer necessary (we were using it to prevent fake accounts from accessing the site). Since SocialLogin was on hiatus for a very long time it had not been updated for this change, therefore it was expecting a field that's not there which is why the old version doesn't work. When the new version is released this issue will resolve itself without further actions on your part.
