### ISSUE TITLE
Changing Bypass user validation param takes no effect

### ISSUE THREAD

**Issue by Sulpher** [akeeba/sociallogin#27]
I tried to enable and disable Bypass user validation param in all plugins (FB, G+ and Twitter), but the result is the same - the system sends a notification at e-mail with an activation link. As far as I understood, this option should enable or disable such kind of checking.

Step-by-step actions:
I enable Bypass user validation param and get activation URL at the e-mail if the user does not exist. I remove this non-active user to reproduce this action again. Then I go back to the plugin settings and disable Bypass user validation param. After logging in I get the same activation URL anyway.
I suppose, there should be automatic user activation without confirming via e-mail...

Expected result:
I need to disable validation via e-mail and allow new users to log in without additional actions.

**Comment by nikosdion** [comment]
This feature works just fine and I cannot reproduce this problem. There is, however, a small caveat. The remote service (Facebook, Google+, Twitter etc) **MUST** report that they have verified the user's account on their end. Otherwise we are not sure that the email address is legitimate, therefore we have to send the Joomla! email _despite_ your setting.

On Facebook, for example, this requires verifying either your email address or your cellphone. This grants you the verified status.

With a Google account you actually need to have a Google+ account with the same email address. Otherwise Google does _not_ report that any of your email addresses is an "account email" which is how it lets us know an account is verified on their end.

Regarding Twitter, I already explained that it won't return the email address unless you ask that permission. If you do ask that permission and the email is returned we know that Twitter has verified it on their end.
