### ISSUE TITLE
Missing english language files

### ISSUE THREAD

**Issue by Cyrusxxx** [akeeba/sociallogin#29]
Hello Nicholas, I would like to report that English language files are missing in download package.
Also Nicholas, can you tell me did something change in code for template override since with 2.0 version
no matter where I insert this code:

`<?php if (class_exists('SocialLoginHelperIntegrations')) echo SocialLoginHelperIntegrations::getSocialLoginButtons() ?>`

Social buttons wont appear.

If you want I can provide you with admin info for you to inspect.
Thank you.

Joomla 3.8.2
T3 Framework 2.7.0
PHP 7.1.4

**Comment by nikosdion** [comment]
Thanks for the heads up about the languages, I'll make a new release.

Regarding the other issue, since version 2.0 you have to use 
```php
<?php if (class_exists('Akeeba\\SocialLogin\\Library\\Helper\\Integrations')) echo \Akeeba\SocialLogin\Library\Helper\Integrations::getSocialLoginButtons() ?>
```

The new version I will publish will also include a class alias `SocialLoginHelperIntegrations` pointing to the new class `\Akeeba\SocialLogin\Library\Helper\Integrations` so existing code won't break. I will also update the documentation.

**Comment by Cyrusxxx** [comment]
Thank you Nicholas, for the quick response. I will use new string. 

Kind regards, Goran.
