### ISSUE TITLE
Displaying buttons

### ISSUE THREAD

**Issue by Cyrusxxx** [akeeba/sociallogin#30]
### Steps to reproduce the issue
Hello Nicholas, I can confirm that inserting new code from this issue:
https://github.com/akeeba/sociallogin/issues/29#event-1380331351
is still present.
I have tested with 1.0.2 version which works but with 2.0.1 it is not.

Thank you!

**Comment by nikosdion** [comment]
Please update your code per https://github.com/akeeba/sociallogin/wiki/Integrating-with-template-overrides

**Comment by Cyrusxxx** [comment]
Nope neither new or old code is working with version 2.0.1:
`<?php if (class_exists('SocialLoginHelperIntegrations')) echo SocialLoginHelperIntegrations::getSocialLoginButtons() ?>

<?php if (class_exists('Akeeba\\SocialLogin\\Library\\Helper\\Integrations')) echo \Akeeba\SocialLogin\Library\Helper\Integrations::getSocialLoginButtons() ?>`

**Comment by nikosdion** [comment]
Try installing the package of version 2.0.1 twice in a row, without uninstalling before in between. Make sure the system plugin is enabled.

**Comment by nikosdion** [comment]
Also note that the code in the documentation is the same code used in the plugin itself. I logged in to my dev sites today using Facebook.

**Comment by Cyrusxxx** [comment]
Update I have set up clean Joomla 3.8.2 with nothing using default template Protostar. PHP version is 7.1.4. I have installed 2.0.1 version of plugin 
I can confirm this as an issue, template overrides are not working auto inserting option also not working when enabling error reports in Global configuration of Joomla I have 2 errors related to this plugin maybe it helps:
`Warning: include_once(/home3/p7c2d9v1/akeeba.regenesiscomputers.com/plugins/system/sociallogin/abstraction.php): failed to open stream: No such file or directory in /home3/p7c2d9v1/akeeba.regenesiscomputers.com/plugins/system/sociallogin/sociallogin.php on line 18

Warning: include_once(): Failed opening '/xxxxxxxxx/plugins/system/sociallogin/abstraction.php' for inclusion (include_path='.:/opt/php71/lib/php') in /xxxxxxxxxxxxxx/plugins/system/sociallogin/sociallogin.php on line 18`

When installed version 1.0.2 everything works.
I dont know what your version of Joomla looks like Nicholas but it doesnt work for me at all.

**Comment by nikosdion** [comment]
I already told you this issue cannot be reproduced. I don't understand why you insist on wasting my time. Anyway, instead of implementing GitHub authentication let's waste some time to prove that this issue does not exist, shall we?

I created a new template override `templates/protostar/html/com_users/login/default_login.php` for the file `components/com_users/views/login/tmpl/default.php`. On line 85 I added the code from [the documentation](https://github.com/akeeba/sociallogin/wiki/Integrating-with-template-overrides):
```php
<?php if (class_exists('Akeeba\\SocialLogin\\Library\\Helper\\Integrations')) echo \Akeeba\SocialLogin\Library\Helper\Integrations::getSocialLoginButtons() ?>
```

Here is the code:
![image](https://user-images.githubusercontent.com/256041/33937079-b2203ccc-e00a-11e7-88f6-b9c7d413f154.png)

Here is the result: 
![image](https://user-images.githubusercontent.com/256041/33937095-c23126d0-e00a-11e7-9d90-9dee0ba1e8f9.png)

As for version 2.0.1, of course my trick for the old code works as well:

Code:
![image](https://user-images.githubusercontent.com/256041/33937139-fb91970c-e00a-11e7-9f59-16a45a3c99a6.png)

Result:
![image](https://user-images.githubusercontent.com/256041/33937156-09b6d040-e00b-11e7-8584-d23f044b5a11.png)

As a result I will insist that this issue does NOT exist. You have screwed something up. Wrong template override? Wrong copy/paste? Code cache? I don't know and, frankly, it's not my job to know, it's yours.

**Comment by nikosdion** [comment]
I am locking this conversation since the issue is invalid.
