### ISSUE TITLE
[suggestion] GDPR compliance: add a new event plugin

### ISSUE THREAD

**Issue by Sulpher** [akeeba/sociallogin#38]
Hi Nicholas,

Using social media account is a way to register on the site in a few clicks which saves user's time and just great, but.. There is a BIG PROBLEM because of GDPR.
A user should accept Terms of Use and we should think about how to display Opt-In in a case of social buttons.

I thought what is possible to do and one idea came to my mind.

Let's consider there is a system/content plugin which makes all Akeeba Social Login buttons inactive and displays checkbox below these buttons. Once the checkbox is checked, the buttons became active and the user can log in / register to the site.

In theory, it should not be a problem to develop such plugin. Of course, if someone does not need such a feature, the plugin can be disabled.
What do you think?

**Comment by Sulpher** [comment]
I am attaching some screenshots to illustrate my idea.

![screen shot 2018-07-08 at 19 44 22](https://user-images.githubusercontent.com/3432048/42422023-c787b2cc-82e7-11e8-91d2-b13464578344.png)
![screen shot 2018-07-08 at 19 42 47](https://user-images.githubusercontent.com/3432048/42422025-cd90d450-82e7-11e8-813b-079ac22a6f84.png)

Suggested params and features for new plugin:
1. Language string for "Accept terms of use" paragraph (language string can be overridden via Joomla)
2. Check out GeoIP and make the plugin working for residents of specified / EU countries only.

**Comment by nikosdion** [comment]
I have already thought of it but there is a problem. You cannot record the user’s preference in an audit log (mandatory under GDPR) unless there is already a user account on your system. Otherwise it is not a reliably recorded explicit consent which is as though as the user has not provided consent.

There are two workarounds.

The first is to let the user create a new user account through social login and then present them the GDPR consent screen. If they do not consent they cannot use the site (but they are given the option to remove their account). Since at this point they have not provided consent you are not processing their personal information so you comply with the letter of the law. That’s how Joomla! 3.9 will work (since its ideas are based on Akeeba Data Compliance which we use on our site). This solution is PROBABLY legal. Since the law has never been tested in a court of law we can’t say for sure if that approach is legal or at least legal in all circumstances. I have to note that major players on the Internet use exactly this approach: you create the account using social media and then they ask you to agree to processing for using your account.

The other way is the “play it safe” approach. Don’t allow people to create new accounts with SocialLogin. Only allow them to link their existing user accounts to a social login profile. This means that they have gone through the acceptance of your personal data policy before linking their social media accounts to their user account. The drawback to that definitely legal approach is that it is still a pain in the butt.

This is why I have decided not to implement a feature like the one you proposed: it would be illegal and solve nothing. Having a reliable audit log for the explicit acceptance of personal information processing is of paramount importance. What you MUST make sure is that if someone has not yet accepted their personal information to be processed you must never, ever let them log in or send them newsletters etc. Their account has to be effectively locked until they give explicit consent (and effectively block them again if they withdraw their consent).

**Comment by Ruud68** [comment]
> The other way is the “play it safe” approach. Don’t allow people to create new accounts with SocialLogin. 

That is how I changed it on my website. Back to relying on Joomla to handle the GDPR requirements for new accounts (and with the upcoming 3.9 this will be out-of-the-box).

But I think that this is also a breach in privacy because when a unregistered user presses e.g. the facebook button, a lot of information for this user is then shared with facebook. That is because the check is done **after** the connection to facebook has been made (to get the email address). So the 'harm' is already done for hat user.

Correct?

**Comment by nikosdion** [comment]
Wrong.

No personally identifiable information leaves your site to the social network. The data flow is the other way around.

In the first case your site _does_ receive personally identifiable information before the user positively accepts the personal data protection policy. This might or might not be GDPR compliant. The legality hinges on the fact that at this point your user has explicitly requested that you receive this personal information (on the social network's page) and you are not processing this information in any way until the user explicitly allows you to. It's convenient for users and site owners and what every major player does right now (e.g. Spotify, Lyft to name but two services I tried recently) but **it has not been tested in court**. The latter part is important. Since this whole thing hinges on interpretations of the law it needs to be tested in court before any of us can say that it's perfectly legal to use. I wouldn't use it on my site and, to be honest, if GDPR had happened _before_ I started writing this code in 2016 I would have not bothered writing SocialLogin at all since this is **exactly** the reason I wanted this solution: remove the signup friction on my site. Grunt...

Hence the second case, the "play it safe". In this case you can't link your account to a social network login before you are fully logged in (have accepted the personal data protection policy). If you are an unregistered user nothing about you is sent to the social network. If you complete the log in and come back to the site SocialLogin sees that you're not registered and discards the temporary account identifier sent to it by the social network. This is the same as someone sending you unsolicited personal information by email, phone etc: you tell them you cannot accept unsolicited personal information and discard the transmitted information. This is not just allowed but _required_ by the GDPR.

**Comment by CodeOfConduct** [comment]
I’m not a lawyer, but to my knowledge there has been, even before the GDPR came into force on 25/5, a legal requirement in a significant number of countries to obtain a user‘s consent to process his/her personal data *before* it is stored and processed. Some countries allow(ed) opt-out (i.e. preselected checkbox) as an expression of consent, others require an opt-in (checkbox needs to be unticked by default so that the user has to actively tick it). As of 25/5, in situations where the GDPR applies, prior consent by opt-in is legally required. In addition, a requirement is that the site operator (data controller) has to document in detail how and when consent was given (or withdrawn). This is not specific to social logins / registrations - it applies equally to any other situation where personal data is collected on a site, e.g. through a contact form. 

Nicholas: I don’t follow your argument “You cannot record the user’s preference in an audit log (mandatory under GDPR) unless there is already a user account on your system.” I agree that audit logs are mandatory, but I don’t see why the user has to have an account on the system before his/her consent can be captured (together with the currently applicable privacy policy details and the consent message text, all with time stamp). Cannot that consent data (=initial preference data for the particular social network with which s/he registers on the site) be captured at the same time when the social network data is stored during account creation?

So, imo Sulpher’s suggestion is still a valid one.

**Comment by nikosdion** [comment]
What happened before the GDPR is irrelevant since we are not going back in time. I can tell you that allowing people to create user accounts with social network logins was NOT illegal (implied consent was good enough).

The GDPR complicated things because you need explicit consent. Is the consent you give on the social network, e.g. Facebook, explicit for the GDPR? Major web properties in the EU with expensive lawyers have determined that yes, it is. Hence my recommendations. 

I will tell you why the proposed solution is legally invalid with an example **under the assumption that you must provide explicit consent on the site before creating a user account**. Please note that I understand that this assumption is INCORRECT. But in the interest of humoring your concerns I will provide a technical analysis under this assumption. Keep in mind that if this assumption is incorrect then we need no change in Social Login.

Example: Person A can click the consent checkbox, hand the device to person B, person B logs into Facebook and a user account is created. In this case the consent would be legally invalid. The data subject did not provide their consent.

What we need to do is more complicated. We receive a single use token from Facebook which we have to use to retrieve a pseudonymous Facebook ID (let's call it PID). We can now check if the PID matches an existing user of the site. If it does we log them in. This is what we currently do.

The difference is in what happens when the PID does not exist. With the existing code we'd retrieve the user's PII from Facebook (since he has consented to that _on Facebook_) and check if their email address exists on our site. Under your operating assumption that this is illegal we need to ask the user for consent to retrieve their email address from Facebook to perform this check. This has a few problems:

1. We need a component to render that page. SocialLogin is currently a set of plugins but plugins cannot render a page. This introduces a complication both for the developer (me) and for the site integrator (you) who has to provide a publicly accessible but hidden menu item for the SocialLogin component.
1. Joomla! has currently no framework for recording this kind of consent. Even third party extensions do not have provisions for recording this type of consent. Therefore we'd have to duplicate functionality from Akeeba Data Compliance to manage this type of consent. This is several days worth of work.
1. Even though we record the consent we can only record it against an IP address and a date/time stamp. This is problematic if several people connect to the Internet from the same external IP at the same time e.g. coffee shop or airport. This makes this kind of recorded consent hairy at best, invalid at worst. Remember that at this point we don't have a user record so we can't link this consent to a specific user.

We obtain consent and we check the email address of the user. If it exists on our site we log them in. But what if it does not?

At this point we need to ask them for consent _again_, this time to create a user account on the site. The same problems as above remain, with one additional problem: your site may be requiring providing consent for more nuanced data processing. This can only be provided through Joomla's account creation page. In an ideal world we'd be able to redirect the user to a Joomla user account creation page prefilled with the information we retrieved from Facebook. However, we cannot. So all we could do is instead of asking for their consent to send them to the blank user profile creation page of Joomla.

At this point we have to sit back and ask ourselves: are we being daft? What was the point of writing a super complicated solution which makes it harder for the developer, the site integrator and the site visitor to use SocialLogin? Isn't the end result the same as NOT allowing user profile creation through SocialLogin?

In fact, that's _exactly_ what it is. It's a complicated equivalent of the second workaround I proposed ("play it safe"), i.e. not allow SocialLogin to create user accounts or login people who have not already linked their Joomla! user account to the social network login. 

So why should I waste my time implementing something which solves no problem, introduces a metric ton of complicated code and can be avoided by disabling two options?! The answer is that I have zero reason to do so and that's why I am not going to do that.
