### ISSUE TITLE
Facebook Login

### ISSUE THREAD

**Issue by kostalasa** [akeeba/sociallogin#39]
### Steps to reproduce the issue

Publish Facebook login and enable option to create new users

### Expected result
A new user account should be created

### Actual result
Facebook plugin thoughts message: You do not have an account on this site that corresponds to this Facebook account. 

Linking from within profile works just fine.

### System information (as much as possible)
* **Joomla! version**: LATEST (3.8.10)
* **Database type**: MySQL, 
* **Server type**: Apache, 

* **Am I using HTTPS**: Yes 
* **Server Operating System**:  Linux, 

* **Am I using HTTPS**: Yes 
* **Server Operating System**:  Linux, 
* **Browser**: Chrome
* **Browser version**: Latest

**Comment by nikosdion** [comment]
Cannot reproduce. Guys, this is a recurring non-issue because you do not read [the documentation](https://github.com/akeeba/sociallogin/wiki/Facebook) carefully.

You need to enable "Allow social login to non-linked accounts" and "Create new user accounts". The latter is an extension of the former. If your site is set up to not allow user creation you need to also enable "Ignore Joomla! setting for creating user accounts".

**Comment by merszel** [comment]
I am facing exactly the same issue, I have followed the documentation step by step to create a Facebook APP, both options "Allow social login to non-linked accounts" and "Create new user accounts" in the "Akeeba Social Login - Facebook integration" plugin are enabled.

Maybe there were some changes in the Facebook Login API recently that require a plugin update?
https://developers.facebook.com/docs/facebook-login/changelog#2018-07-02

**Comment by kostalasa** [comment]
Yes, I can confirm that I am still facing the same issue even after the recommended changes.

**Comment by nikosdion** [comment]
No, the API changes do not have an effect. As you can see on the table, the name and email fields (the only fields used by our plugin) are available even without app review. As I have already told you, I have tested these instructions and they do work. I have a test site at https://myoldsite.com/ which has that setup. You can go ahead and try it yourselves, guys.

Please do keep in mind that in order to automatically create a user account through Facebook login your Facebook account must be **validated**. This means that you must have gone through the email verification from Facebook and enter a valid phone number. Unvalidated accounts can very easily be spam / throwaway accounts and we can't allow them registering a Joomla! user.

Finally, I would like to point out that this issue has been filed before several times. The fact remains that the problem is not with the plugin but with your setup: on your site, your Facebook app or your Facebook account. That's outside my control. Also note that I _have_ updated the Wiki last time Facebook changed the way apps are set up. So... check your FB setup?

**Comment by mubmart7** [comment]
The problem is with not adding Email as one of the data you will be collecting in the App Review.

![Screenshot 2023-08-06 at 14-48-40 (1) Lafab Solutions - Use cases - Meta for Developers](https://github.com/akeeba/sociallogin/assets/141418802/37e6fc72-74b2-4910-8754-539d8b377774)
![Screenshot 2023-08-06 at 14-49-11 (1) Select app permissions - Meta for Developers](https://github.com/akeeba/sociallogin/assets/141418802/927634bd-2e78-4a1b-b179-a1ca1e6ec942)
