### ISSUE TITLE
Bad redirect link with Facebook

### ISSUE THREAD

**Issue by uzielweb** [akeeba/sociallogin#40]
### Steps to reproduce the issue

Create app in Facebook

### Expected result

Redirect to registration/login page
https://www.facebook.com/dialog/oauth?response_type=code&client_id=469549133525122&redirect_uri=https%3A%2F%2Fwww.fritonobalde.com.br%2Findex.php%3Foption%3Dcom_ajax%26group%3Dsociallogin%26plugin%3Dfacebook%26format%3Draw&scope=public_profile%2Cemail

### Actual result
URL blocked: The redirection failed because the URl used is not in the release list in the application client's OAuth settings. Verify that client and web OAuth login is enabled and add all domains in your application as valid OAuth redirect URLs.

### System information (as much as possible)
Joomla 3.8.11
PHP 7.2

**Comment by nikosdion** [comment]
The error message tells you that you have not configured your Facebook app correctly _on Facebook's site_. Please read the documentation Wiki more carefully and follow its instructions. **BE VERY CAREFUL** when entering the URLs. The documentation contains samples with a fake domain name.

**Comment by uzielweb** [comment]
But in insert the redirect and nothing works.
Facebook >>> I hate it.

**Comment by nikosdion** [comment]
I recommend trying to set up a new Facebook app from scratch, following [the documentation](
https://github.com/akeeba/sociallogin/wiki/Facebook) to the letter. 

The order of operations is very important. You cannot enter a redirect URI until you have finished setting up the App Domains. Even then, the redirect URI you are entering must be in a domain you have already set up.  Based on what you are saying the problem is that you didn’t enter the exact domain in the App Domains page which is why you cannot enter a redirect URI. Having not entered a redirect URI Facebook complains when you try to log in with Social Login since the redirection it sees does not match its (empty) list of configured redirection URIs.

Yes, Facebook is a pain in the posterior to set up. So is Google. Everything else I’ve implemented so far is much easier to set up. However, everything else I’ve set up has much more limited scope in their services than FB and G, so there’s that.
