### ISSUE TITLE
Facebook login - help/clarification needed.

### ISSUE THREAD

**Issue by okanime** [akeeba/sociallogin#42]
###
I am having some difficulty with this. I have created the several fb apps trying to figure out what's wrong with my setup.

**My Settings:** 
Allow social login to non-linked accounts: Yes
Create new user accounts: Yes
Ignore Joomla! setting for creating user accounts: Yes
Bypass user validation for verified Facebook users: Yes
Button styling: Yes
_(even toggling these settings, didn't work)_

The plugin goes to facebook app and connects successfully, however once it redirects back to my website instead of loging in the user, it shows this statement instead **"Warning
You do not have an account on this site that corresponds to this Facebook account."**  

I have toggled all possible FB app settings and I've created several other FB app to test this and still it persists with no successful login.

Any help or shove towards the right direction would be very much appreciate.

Thanks!

### Expected result
Login and create user.

### Actual result
No login.
Throws an error: **"Warning
You do not have an account on this site that corresponds to this Facebook account."**

### System information (as much as possible)
* **Joomla! version**: 3.8.11
* **Database type**: MySQL
* **Server type**: Apache, NginX, IIS, Lighttpd, LiteSpeed, ...
* **Hosting company / Local server**: Hostgator
* **Am I using HTTPS**: Yes
* **Server Operating System**: Linux
* **Browser**: Chrome, Safari

**Comment by nikosdion** [comment]
Go to https://myoldsite.com/ and try logging in (basically, creating an account and logging in) with Facebook. If you get a message that you need to verify you remail address it means that your Facebook account is NOT validated. Therefore it cannot be used to automatically create a new user account. In this case, if you have also disabled user account creation using the "self" validation method in your Joomla! site you will receive the error message you pasted in this issue. The reason is simple: an non-validated FB account can be registered against an email address not owned by the person claiming to be using it. Therefore it cannot be trusted. As a result we'd need to validate their email address through Joomla!. If the user creation is turned off OR the user validation is set to Admin we can't proceed with the email validation. The only reasonable action in this case is to deny the creation of a user account for reasons of privacy and account security.

If you validate your Facebook account (e.g. by entering a phone number and confirming the code in the text message you receive) you can of course create a new Joomla! account.

**Comment by okanime** [comment]
Thank you for your quick response. After setting up another FB App and using 2 different FB accounts (one with a verified phone number and email and another without) unfortunately this issue remains.

I have also disabled creation of user account via the FB login and still this issue persists.

I've meticulously followed every step and still no success. All the other logins Twitter and the rest are working perfectly except for FB.

If there is any other work around you can suggest, I am willing to give it a shot.

Thanks again!

**Comment by nikosdion** [comment]
Have you tried the site I gave you? That’s my test site using a FB app I’ve set up myself. I want to know if your _verified_ FB account works there. If it does we can start trying to see what you configured wrong. If not, tell me how you verified your account so I can try to reproduce the issue and see what’s going on.

**Comment by okanime** [comment]
Its in development mode. 

⁣

**Comment by nikosdion** [comment]
Sorry about that. FB changed a few things since I last looked into that app and I had to provide a GDPR contact and privacy information to set it back to live. Now it's live again. Please give it a try.

I tested myself with two different FB accounts:
* **Verified account**: a new Joomla! user was created, activated and logged in automatically.
* **Unverified account**: I got the expected error “
You do not have an account on this site that corresponds to this Facebook account.”.

Please note that the email address on either account did NOT correspond to an existing user of the site. That was on purpose since I was trying to establish whether you can create a new user through Facebook (the issue you reported).

**Comment by nikosdion** [comment]
![image](https://user-images.githubusercontent.com/256041/44397484-295daa00-a549-11e8-86fd-a8dbd668ed78.png)

![image](https://user-images.githubusercontent.com/256041/44397515-47c3a580-a549-11e8-94f3-bb4eeadaf25b.png)

**Comment by okanime** [comment]
Thank you for sharing these settings. 
Unfortunately mirroring your settings did not fix my problem. I am going to leave the Facebook option for now because I don't know what I'm missing.

I will setup a clean install of Joomla on the same server and run nothing but your plugin. I will report back to this thread once I have done that.

**Comment by okanime** [comment]
Report back. After a new Joomla installation on the same server and a new fb app, this issue still persists.

**Comment by nikosdion** [comment]
Well, you've tried my site which works. The instructions I wrote in the wiki is exactly how I set up that particular site. Therefore it is perfectly reasonable to assume that if you follow my instructions you will get something which works.

I cannot follow the instructions for you. The way Facebook works you need access to the Facebook account which owns the app to do anything useful.

I will lock this issue since it is not an issue with the software and I cannot help with anything beyond the code I've written (and even that I can only really do if you provide steps which allow me to reproduce your issue which, clearly, is not the case here).
