### ISSUE TITLE
No Account on Site Warning 

### ISSUE THREAD

**Issue by nzampella** [akeeba/sociallogin#43]
Nicholas,

I realize that you've stopped development on this plugin due to the European privacy concerns.  However, here in the US, we don't have those issues, and I would like to see about what is needed to get this fixed.    

I had the plugin installed on this one site I was building for a class reunion group back in Feb 2018, and it was working fine.     Had to stop work there because of personal issues with one of the event organizers.  She's better now, and we want to move forward, but this error keeps coming up.  It will not create an account nor log into the site to an existing account.    I updated to the last released version 2.0.3 found here on github, but still no joy.

I have checked all the settings on FB, and in the plugin.  I created an account on the site with the same email address as on FB, and it still will not connect.     I'm willing to manually adjust the source myself to get this fixed, but need an idea of where to start.

Any pointers on this would be appreciated.

Thanks,

Neil Zampella
Longtime Akeeba Subscriber

![facebook](https://user-images.githubusercontent.com/11995082/55297879-3e13f180-53f8-11e9-9b09-2b84d389a8da.PNG)

**Comment by nikosdion** [comment]
First of all, I have reopened this repository and started work on it again as you can see in the Code tab at the top.

Second, GDPR has to do with nationality, not geographic presence. If I come to the USA and access your site I am still protected by the GDPR. If I access your site from Europe I am still protected by GDPR. That's the thing about GDPR; you cannot ignore it even if you have nothing to do with Europe; one of your visitors might have the nationality that protects them under the GDPR. Since there's information exchange and judicial assistance between the USA and EU it kinda makes sense for American sites to implement GDPR lest they get sued :)

Regarding your issue, I have already said that it's due to an API change and I have already fixed it with https://github.com/akeeba/sociallogin/commit/cf35f3825b7cef8c41506f889fd760b266d570ad I will publish a new release soon.
