### ISSUE TITLE
OpenID Support

### ISSUE THREAD

**Issue by neo191987** [akeeba/sociallogin#44]
Hi, is it possible to add OpenID support.  I want to add Steam Login and he does not support this library. I do not know why they use this authentication method :( Generally, writing authentication plugins is not very complicated, so in the future I can do a few plugins. :)

**Comment by nikosdion** [comment]
I am not really interested in implementing OpenID mostly due to lack of time and the fact that I don't have a business case for it. That said, I won't turn down a Steam login plugin if a kind soul decides to donate the code to me (hint hint wink wink).

If you want to do it yourself you can use something like https://github.com/jumbojett/OpenID-Connect-PHP as the client implementation and follow the example of the new SocialLogin plugins -- they are _dead_ simple. They are simpler to write than Joomla authentication plugins. You will basically need to create a method that maps OpenID fields to SocialLogin fields. The rest of it is common code that's tucked away in the abstract plugin.

**Comment by neo191987** [comment]
Thank you for the reply. I found something interesting that can help create new plug-ins. View this link: [https://github.com/hybridauth/hybridauth](url)

**Comment by nikosdion** [comment]
If you don't understand why this is a bad idea in the context of Joomla authentication please don't try making any authentication or social login plugins yourself, you will introduce security vulnerabilities.
