### ISSUE TITLE
Errors in console

### ISSUE THREAD

**Issue by Sulpher** [akeeba/sociallogin#50]
I've installed the latest version 3.0.1  get the following errors in console:

buttons.js:17 Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Element': The provided selector is empty.
    at akeeba_sociallogin_findField (https:site.com/media/plg_system_sociallogin/js/dist/buttons.js:18:25)
    at akeeba_sociallogin_lookInParentElementsForField (https://site.com/media/plg_system_sociallogin/js/dist/buttons.js:60:19)
    at akeeba_sociallogin_move_button (https://site..com/media/plg_system_sociallogin/js/dist/buttons.js:99:18)

### Additional comments

Also, I noticed the extension requires Jquery. For why? 
It would be better to avoid using Jquery, especially in perspective of J4. 
Thanks.

**Comment by nikosdion** [comment]
This shouldn't be a problem. It is part of the JS which tries to figure out possible places where login action buttons exist in order to inject its own. Could error handling be improved? Sure. I don't have the time to do that and, frankly, since it causes no functional problem I have no incentive either.

There is a very good reason using jQuery. It is very well tested among all browsers and their versions. It will work consistently no matter if you're using something ancient like IE9 or something modern like the latest version of Chrome or Firefox. Expecting third party developers to write vanilla JS with that level of browser support is unrealistic. Remember, we had that experience as a community 12 years ago which is why Joomla 1.6 started bundling jQuery in the core. It took another 5 years for developers to stop bundling their own version of jQuery with their extensions. I believe that also answers your question about Joomla! 4.

If you want to you can always override my JS files with your own. However, once you do that, any problem is on you and I can no longer help you.

**Comment by Sulpher** [comment]
I am reporting what I noticed to help developers making the products better. It is not a big deal, but it could be fixed someday. 

Your script button.js does not use Javascript, but window.jQuery inserts to <head> tag in inline scripts. Since the script does not use jQuery, it would be better to fix the script to the unified style. 

Btw, the corporate sector requires IE11. IE9 is obsolete.

**Comment by nikosdion** [comment]
It depends on the company. IE9 is pretty much still alive (unfortunately) in the public sector. IE11 is not that much better. Anyone who's tried applying event handlers will know that IE, even 11, is rather "special".

In any case, I am not going to waste my time trying to replicate in vanilla JS what jQuery already does. My code will never be anywhere near as fully tested as jQuery and no, the performance difference is negligible since I don't do the silly thing of using the same selector with the jQuery constructor over and over (that's what most people do wrong and give jQuery a bad name).

If you want to contribute an alternative to jQuery feel free to do so. I will evaluate your solution and tell you if it can be accepted. I just won't start changing things **for the sake of changing things**. I don't have infinite time and I'd rather the limited time I do have productively.
