### ISSUE TITLE
Redirects to #_=_

### ISSUE THREAD

**Issue by interkrok** [akeeba/sociallogin#52]
Hey, 

Not sure if it is our site instance but after existing facebook user logs in on our site it redirects to mysite.com/#_=_

So Facebook managers rejected our App publication because of that reason.

We read your guidelines briefly and didn't find related information about such case.
I would appreciate you advise VERY much!

p.s. will be glad to leave any kind of review on JED

**Comment by nikosdion** [comment]
That's where Facebook redirects you.

**Comment by eurtnl** [comment]
Hi,
I'm facing the same problem. Where should I put the redirect URL other than in Joomla?

**Comment by nikosdion** [comment]
Please do read https://github.com/akeeba/sociallogin/wiki/Facebook You need to enter the redirect URL **in your Facebook application**. If it's not entered correctly you will end up with this issue.

**Comment by eurtnl** [comment]
I'm not sure where to enter the redirect URL.
Should it be in "Valid OAuth Redirect URIs" because I already tried that and no succes.

**Comment by nikosdion** [comment]
That's where it should be. What is the URL you have entered there?

Also, what is the URL of the page on your site where you click the Login with Facebook button?

Please give me exact, unredacted URL. I need that to understand better what is going on since I've not been able to reproduce this issue with any other site under my control.

**Comment by eurtnl** [comment]
The URL I entert is: https://www.pitch-putt.net/index.php?option=com_ajax&group=sociallogin&plugin=facebook&format=raw
The button is on the login page: https://www.pitch-putt.net/index.php?option=com_users&view=login

And I want the users after login redirect to https://www.pitch-putt.net/index.php?option=com_kunena&view=home&defaultmenu=220

**Comment by nikosdion** [comment]
What you are trying to do is not possible in Joomla. SocialLogin will redirect you back to the page you used to log into your site (the page on which you clicked the Login with Facebook button). Facebook also adds the `#_=_` part of the URL which cannot be removed (PHP doesn't have access to the URL fragment, i.e. anything from the hash sign onwards).

The reason why what you're trying to do won't work is that Joomla 3 **DOES NOT** support third party login buttons. What we're doing, as explained in the documentation wiki, is a bit of sleight of hand using JavaScript. We create our own buttons outside Joomla's form and move them to visually appear inside the form. However, the server side which generates the login buttons does NOT have the redirection URL specified in the login module. The only URL it knows is the current page URL. So this is all it can use to generate the special URL to log in with Facebook.

Joomla 4 does allow us to create custom login buttons but, again, the redirect URL is not communicated to the plugins creating the login buttons. Even though the buttons are created inside the login form they cannot make use of the redirection URL you specified in the login module.

So, neither of you are actually having an issue with SocialLogin. The problem is that Joomla doesn't allow you to do custom redirections with non-email login buttons AND that Facebook always adds the `#_=_` fragment. One is up to Joomla to fix and the other up to Facebook. I wouldn't hold my breath for either...

**Comment by nikosdion** [comment]
Side note: You CAN of course use Social Login to redirect to whichever URL you want BUT you need to create a template override for `mod_login` or whichever login module you are using as explained in https://github.com/akeeba/sociallogin/wiki/Integrating-with-template-overrides#adding-login-buttons.

The reason is that the template override of the login module _is communicated the actual redirection URL for login success and failure_. Therefore you can send that information in your `\Akeeba\SocialLogin\Library\Helper\Integrations::getSocialLoginButtons()` method call which, of course, instructs whichever login method you use (e.g. Facebook) to redirect you to the correct URL.

So, the only way to do this is with a template override. It is not possible to do it "magically" through the plugin without any effort on your part. That's how Joomla is designed, folks.

Moreover, you can NOT remove the `#_=_` part of the URL when you are redirected back to your site. This is added by Facebook. No idea why. It just does.

I hope that helps.

**Comment by eurtnl** [comment]
Ok, thank you very much for the explanation. I'll have a look at the template overrides.
