### ISSUE TITLE
[Mobile app] - Facebook login

### ISSUE THREAD

**Issue by astronnx** [akeeba/sociallogin#53]
Hi.

In first place, thanks for this plugin! Is amazing! ;)
I have a quetion....
Is it possible, when you are browsing from a mobile phone, that the login be done through the native app (facebook, google account..) instead of the browser?

Thanks.
Best Regards.

**Comment by nikosdion** [comment]
No. This can only work if you use the service's JavaScript libraries to implement the login buttons.

First, that'd be a major performance issue. For example, Facebook loads about 1MB of JavaScript code to implement the Login with Facebook / Continue as YourName button.

Second, this method is in violation of the EU GDPR / CCPA because these JS login buttons collect personally identifiable information (PII) from all visitors to your site. In order to be compliant you would have to NOT display these buttons UNTIL the user explicitly agrees to sharing the personally identifiable information with the specific service. That would make integration a nightmare and the overall user experience would be abysmal. As a visitor you'd first see a modal which asks you to share your personally identifiable information in which you'd have to select, e.g. Facebook. Then the page would reload and the login button appear. You click on it and you get transferred to a different app. You accept the login there and you're back in the browser. I reckon you've lost your visitors.

Conversely, the way we are implementing the buttons has neither of these issues.

No JS is loaded. The button is a simple link to the service's OAuth2 consent page. That's less than 200 bytes and doesn't require any JavaScript to run and slow down your site. Furthermore, being a simple link, there is no PII collected by the third party service unless the button is explicitly clicked by the user. Depending on the language in your privacy policy and your use case this _can_ be enough to be compliant with GDPR and CCPA.

Also, for what it's worth, it _is_ possible for the third party service to redirect the login to their app if they so choose. However, this depends on the mobile OS, the device's preferences and the mobile app itself. To give you an idea, any iOS 10 or later device with Limit Ad Tracking enabled disables deep linking into applications. On those devices you'll never get the mobile app to open from a web page.

**Comment by astronnx** [comment]
Thanks! But I think that i have not explain good.
Just I want "redirect the login to their app if they so choose".
For example:

1 - User visit my website from his mobile phone
2 - User click on "facebook button" for login or create account from my joomla site.
3 - The answer comes from the native mobile application.

Now, when user from mobile phone doing click on  "facebook button" for login or create account from my joomla site, this login is provided across browser...but i want that this login process be across native app.

Sorry for my level of english :(

I hope that you can understand me

**Comment by nikosdion** [comment]
I understood you correct the first time. I also told you why this is not possible without using the JavaScript login button.

**Comment by astronnx** [comment]
Ok. I understand you.

Thanks a lot!
