### ISSUE TITLE
Login Telegram

### ISSUE THREAD

**Issue by tecnologieinformatiche** [akeeba/sociallogin#56]
**Describe the solution you'd like**
Hi, I would like to have access via Telegram. It's possible? how much does development price?

thanks

**Comment by nikosdion** [comment]
According to the Telegram API page the only way to implement a login is with a widget. Basically, loading a piece of JavaScript from their server on every page loaded on your site. This has two implications.

First, you cannot style the login button. You get what Telegram gives you which is a small, medium or large button. This button cannot be moved around the page which means that on Joomla 3 it will always end up at the very bottom of the login module / login page, on its lonesome. You cannot move it with the rest of the login buttons. On Joomla 4 it will simply not appear at all since you can't tell it to display a piece of JavaScript code instead of a button. This is the first deal breaker.

The second problem is one of privacy and GDPR compliance. The third party JavaScript that is loaded on every page of your site can set its own cookies / local storage and can potentially be used to track users. This means that it cannot be loaded until the user has explicitly accepted this. There is no universal mechanism in Joomla (or any other CMS for that matter...) to do that. Essentially, we'd either create something that's illegal in Europe or we'd need to create a whole GDPR compliance solution larger in scope than even what Akeeba DataCompliance does.

Because of those two reasons I am not willing to implement Telegram login as part of SocialLogin. If Telegram changes their mind and documents their OAuth2 service (which they seem to be using as I am reading in their JavaScript code) we can write a proper integration which will not suffer from the two issues above.

**Comment by tecnologieinformatiche** [comment]
Hi, have you seen this article?

https://core.telegram.org/widgets/login

Thanks for the effort

**Comment by nikosdion** [comment]
It should be pretty obvious that I did read that page since I started my reply by saying "According to the Telegram API page the only way to implement a login is with a widget". The page you linked me to is titled "Telegram Login Widget". Read my reply again. Now read the page you linked me to. Then read my reply again.
