### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by dmleeman** [akeeba/sociallogin#68]
Joomla 3.9.24
PHP7.4.14
UK LItespeed Server hosting

I have an issue whereby the login buttons will not display in the login form when I apply Litespeed cache plugin 1.3.2

Even disabling the cache on the module does not solve it, only on pages where the cache is disabled will the buttons display.

I cannot apply an exception to the Akeeba plugin via the admins, Litespeed cache does not have an option to specify other plugins.

Is it possible for me to add some header into the plugin to allow Litespeed to work its magic on the rest of the site and not interfere with Akeeba SocialLogin?

**Comment by nikosdion** [comment]
Do note that this is **NOT** a problem with SocialLogin itself.

SocialLogin buttons are rendered using JavaScript on Joomla 3 because Joomla 3 lacks support for additional login buttons. 

However, enabling Litespeed caching on your site seems to be causing Javascript trouble on your site. This is not limited to SocialLogin. It's just becoming blatantly obvious with it because you no longer see the login buttons.

I cannot tell you how to fix your Litespeed caching configuration. Ask your host. My guess is that on top of caching it's also reordering JavaScript files on the page, either adding the `defer` attribute or moving them to the bottom of the page. This breaks Joomla 3. At the very least jQuery needs to remain in place, otherwise all head JavaScript breaks.

**Comment by dmleeman** [comment]
Thank you for taking the time to look at it.
I do realise it is not an Akeeba SocialLogin issue and have raised an issue on the Litesepeed forum.
There is a plugin (JCH) that re-orders the javascript and I do see conflicting information around the web on how this is a benefit and a hindrance.
It seems that in the Joomla CMS environment that re-ordering javascripts may not be a great idea.
Given your experience, reputation and quality of code, logically this advice would trump others I have seen so thank you for helping me 'land on a square' with regards to that approach.

**Comment by nikosdion** [comment]
Rearranging JavaScript indiscriminately is _bound_ to cause problems. Joomla normally loads jQuery as a blocking script (no defer, no async) at the head of the page before any inline scripts. This means that inline scripts can safely use jQuery to run code when the browser fires the DOMReady event using jQuery's `$(document).ready()` handy helper. If something moves jQuery into the bottom of the page or marks it as defer or async there is no guarantee that it will be loaded before the inline scripts, therefore it will break JavaScript on the page.

While I could make the same changes to Social Login that I've made to our other software to avoid this problem the downside is that it'd now depend on Akeeba FEF which would add an extra 500KB to the package size and load a lot of JavaScript you don't really need. Otherwise I'd have to duplicate existing work. This makes no sense when Joomla 4 no longer needs that JavaScript-based solution to adding login buttons and under Joomla 3 we already allow you to use template overrides to place the buttons in the HTML output without using JavaScript.

The best approach to fix your issue is using template overrides for the login module and Joomla's com_users login page.

**Comment by dmleeman** [comment]
Your candid explanation is greatly appreciated; thank you.
I can see how it is frustrating for more advanced developers to observe the many 'optimisation' tools that, with anything other than a small to medium 'static' site, cause more problems than they solve.

Great advice on the override path. I shall try that.
Oddly, I can see the CSS and javascript calls in the source code of the site with Litespeed plugin enabled - they simply refuse to render, due no doubt to some unobserved effect of the Litespeed plugin!
However, you have provided me with more than enough to try.

Kind regards
David

**Comment by dmleeman** [comment]
For anyone else who happens across this thread:
Joomla 3.9.25
PHP 7.4.14
Hosted on Litespeed Servers
Akeeba Social Login 3.2.7

Overrides instructions link here: https://github.com/akeeba/sociallogin/wiki/Integrating-with-template-overrides
