### ISSUE TITLE
SVG icon is not loaded

### ISSUE THREAD

**Issue by sakiss** [akeeba/sociallogin#82]
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue
The issue seems to be here:

![double_base_fodler](https://user-images.githubusercontent.com/1838041/137531844-c2b68d17-515c-4c12-9fcb-48119d54714c.png)
The path contains the base folder twice.

### Expected result

Load the svg icons

### Actual result

Null icons

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 4.0.3
* **PHP version**: 7.4
* **Am I using HTTPS**: No
* **Server Operating System**: Linux

### Additional comments
Seems like the `Joomla\Plugin\System\SocialLogin\Features\ButtonInjection` in your release diverges from your repo. Not sure if this is already fixed.

**Comment by nikosdion** [comment]
You are right. It happens if your site is in a subdirectory. Joomla's documentation of HTMLHelper::image is (unsurprisingly...) wrong. I fixed it with the commit above.

Please note that the branch for the development of the Joomla 4 version is currently `feature/joomla4`, not `development`. I need to find a quiet 2–3 days to change the branches across a bazillion repositories and all my machines (my workhorse Mac, a dual boot Windows/Linux laptop, my Linux backup computer and a dev server). Lots of fun...
