### ISSUE TITLE
Social Login buttons appear on backend, but not front end

### ISSUE THREAD

**Issue by ximcix** [akeeba/sociallogin#89]
Greetings.
I tried following the steps as best as I could for Google & Facebook configurations & realized that both Facebook & Google dev pages have changed since the instructions were written. But I still did what I could to get find the setting mentioned in the instruction at it's new location and configured accordingly.

I've switched the app in Live mode and got nothing on my login form.
Later when I go to login to my admin area, there were the social buttons on my back end, but nothing on the front. (see attached screenshots below)

I am using 
Joomla 4.1.5
Akeeba SocialLogin 4.2.0

Please assist.
Regards,

Marlon.

![Screenshot 2022-10-13 192442](https://user-images.githubusercontent.com/22955792/195729424-e6d02ad6-91d6-464b-9a40-bdef2fd9b1a6.png)

![Screenshot 2022-10-13 192233](https://user-images.githubusercontent.com/22955792/195729439-008a74da-c026-4c8c-9f30-5b34d0a4a8df.png)

PS:  I tested them and got this message after click the Facebook login, then clicking "Cancel":
![Screenshot 2022-10-13 191704](https://user-images.githubusercontent.com/22955792/195731237-232fff7d-194d-4e25-aea0-1da4409ac2fe.png)

And a similar error when I used Clicked the Google button:
![Screenshot 2022-10-13 195632](https://user-images.githubusercontent.com/22955792/195732934-46557d1a-9aea-4000-ae2b-4ee5f33bba5a.png)

I was pretty careful to copy the OAuth Redirect URIs specified in the instruction and changing example.com to my actual domain

**Comment by ximcix** [comment]
Hello.
I see that the topic was labeled "invalid" by nikosdion with no explanation.
I'm trying to get help configuring the SocialLogin plugin. If I did something wrong, I'd like to know what I do so that I may correct it.

Thanks for any assistance you can provide.

Best regards,
Marrlon.

**Comment by nikosdion** [comment]
> I tried following the steps as best as I could for Google & Facebook configurations & realized that both Facebook & Google dev pages have changed since the instructions were written.

This is correct and there is a warning at the top of each wiki page that the instructions are _not_ part of the documentation, we are not responsible for third companies' products and we only include a snapshot of how things were when we wrote the documentation to basically give you an idea of where to look.

> I've switched the app in Live mode and got nothing on my login form.

These are completely unrelated things. SocialLogin has no idea if your app is in live mode or not. All it knows is whether you have provided the configuration information it needs to render a button.

> Later when I go to login to my admin area, there were the social buttons on my back end, but nothing on the front. (see attached screenshots below)

The fact that you see something in the backend login module means that the plugins work.

Now, look at that backend login module carefully.

You will see that above SociaLogin's button you have Joomla's Web Authentication button.

Now look at your frontend. You see no button, not even Joomla's Web Authentication button.

This means that you are using a third party component or login module which is not actually Joomla 4 compatible in the sense that it does not support the additional login buttons, a feature added in Joomla 4.0 since the early alphas released around March 2020. Contact the developer of that login module / component and ask them to fix this problem.

Since this is a problem with third party software this is not an issue with SocialLogin which makes it an invalid issue.

**Comment by ximcix** [comment]
Hi nikosdion.
Thanks for your reply & explaining why you labeled the post as invalid.

I'm not sure why you are taking a defensive stance, as I never listed my entry as a "bug" or stated that the software isn't working correctly. I selected the "Anything else" category when creating the topic. I even followed up stating that I am seeking help in case I did something wrong (didn't configure it correctly).
I merely detailed the steps I took, so that anyone reading could see where I made a mistake, if any.
I don't see where my post could came off as an attack or accusation that the software is faulty, but it is not. My apologies if it was interpreted that way. I'm simply asking for help.

My login page is using Joomla's login form, not a 3rd party.
The login page was created via Menus > [Login Menu] Menu Item Type > Users > Login Form.
I also created a test Login module to put on another page and got the same result.

Best Regards,
Marlon.

**Comment by nikosdion** [comment]
Please read https://github.com/akeeba/sociallogin/blob/development/.github/SUPPORT.md You asked for support, you did not report an issue or made a feature request. The correct reply on my part would've been labelling this invalid and closing it. Anything you get beyond that isn't something you're entitled to. Don't try to insult the person who is _already_ helping you even though they don't have a reason to.

Just because the menu item is Joomla's login form doesn't mean that you are not running third party software. Your site has a **template** which is _software in itself, by definition_. This template has **view template overrides**. These can and do control whether additional login buttons are rendered at all. If they are completely missing the necessary code they won't render the darned buttons! I will link you to the necessary code in the original files of Joomla 4.1.5 so you can compare them to your template overrides:

* Login page: https://github.com/joomla/joomla-cms/blob/71389ff3d73122359d3812abaa64f9928ab653cc/components/com_users/tmpl/login/default_login.php#L69-L100
* Login module: https://github.com/joomla/joomla-cms/blob/71389ff3d73122359d3812abaa64f9928ab653cc/modules/mod_login/tmpl/default.php#L102-L129

Beyond the fact that no login buttons — **including Joomla's own WebAuthn passwordless authentication** — are rendered, you are stuck on Joomla 4.1.5 two months after Joomla 4.2 was released. Is it possible that as soon as you tried updating to 4.2 your site broke? That would also be because of the same template overrides. Joomla 4.2 removed the old Two Factor Authentication and replaced it with Multi-factor Authentication. This means that the code `if (count($twofactormethods) > 1)` in your template overrides no longer works. It should read `if (count($twofactormethods ?? []) > 1)` (note the added `?? []`) to make it compatible.

If you fix your template overrides you will get SocialLogin working, you'll get Joomla's WebAuthn passwordless authentication working and you will be able to upgrade to Joomla 4.2 and beyond.

**Comment by ximcix** [comment]
Thank you for you reply.
You are correct and the template is the issue. I switched the template for the Login menu page and the buttons appeared. Now I now have an idea of what to do next.

Joomla suggested updating a couple installed components first before upgrading to v4.2, so I never ran the update.
