### ISSUE TITLE
Akeeba social login problems when log out

### ISSUE THREAD

**Issue by maria-profesora** [akeeba/sociallogin#94]
I there!

I've just installe the latest version of Akeeba Socil Login, because Google is warning me of upcoming changes when login, so i've decided to install thse extension for Joomla.

I've configured it with de google data (client Id and the client secret) up to there everthing it's OK. Then i've specified what login it's going to use. And it works!!! i can log in the application. first i'm asked for the Google user i'm going to log in and works!

The problem comes when i log out, it fails with a 404 window with the message: "You are not authorized to view this resource"

I've tried to redirect when disconnect, creating a new Menu item with a link to de login page, but doesn't not work

I've been lot of hours trying to solve it, but i'm not able.

Please, Can someone help me?

Best Regards!!!

**Comment by nikosdion** [comment]
Hello!

The problem you have is actually with Joomla itself, not SocialLogin. Let me try to explain this with a simple example.

Let's say you have a very basic site with a Home menu item which has its Access set to Public, and another menu item called Secret with its Access set to Registered. The former can be viewed by anyone, regardless of whether they are logged in or not. The latter can only be seen by people who are logged into the site. In both pages let's say there is a login module.

Before you log into the site all you see is the Home menu item.

After you log into the site you can see both Home and Secret.

Let's say you visit the Secret page, read its content and decide to log out. You click on the Log Out button in the login module on that page.

What happens next?

Joomla logs you out and tries to display the Secret page. However, the Secret page has its Access set to Registered, i.e. logged in users only. Since you are not logged in, Joomla gets angry and displays the “You are not authorised to view this resource” error.

In my opinion this is kinda dumb — and preventable, in most cases.

However, this is not something I can fix, it is something which has to be addressed in Joomla itself. For the record, while it's possible to set a logout URL in the Joomla login module to work around this issue I think that this implementation is rather pointless because it requires the user _ somehow knowing_ this optional feature has to be enabled to prevent a very common problem. It's a lot like having a family car equipped with ABS, but having it turned off by default. What good does it do if you need to be experienced enough to know it needs to be turned on, when in this case you'd already know at least half a dozen other ways to address the problem? Sigh…

Please file [a new GitHub issue on Joomla's repository](https://github.com/joomla/joomla-cms/issues/new) and tag @crystalenka. She is the Joomla Experience Team lead. I've already talked to her about this issue. She _needs_ Joomla users like you to submit issues about these quality of life issues so she can hound the maintainers to fix them.

**Comment by maria-profesora** [comment]
Thank's a lot for your help, the example you've writen me is excellent!!!
