### ISSUE TITLE
[OTHER] How to refuse Authentification in certain case

### ISSUE THREAD

**Issue by ariouche** [akeeba/sociallogin#95]
Hi, I've activated Microsoft Azure plugin and works like a charm.

I'd like to know wether it's possible to catch successfull authentification. I'd like to authorize severals users using Microsoft based on Joomla groups or other internal DB logic.

Thanks

**Comment by nikosdion** [comment]
If I understand this correctly, you want to only allow certain user groups (or whatever criteria) to use Login with Microsoft.

Well, you will have to write a `user` plugin which catches Joomla's bog standard `onUserLogin` event which has the signature `public function onUserLogin(array $response, array $options): bool`. The `$response['type']` array element tells you how the user logged in. When a user is being logged in through SocialLogin the value of that array element is the string literal `SocialLogin` (note the capitalisation!). The array element `$response['username']` contains the Joomla username.

From that point you can write your own custom login to accept or reject the login. If you reject the login, return a boolean `false` and Joomla _will not_ proceed with the user login. It is recommended to use `\Joomla\CMS\Factory::getApplication()->enqueueMessage('A user-visible error message', \Joomla\CMS\Application\CMSApplicationInterface::MSG_WARNING)` before returning boolean false to let the user know _why_ their login was rejected. Otherwise, the user will think something randomly broke and they will try over and over again.

**Comment by ariouche** [comment]
Hi, thanks for that!

I successfully catch the event after login. However, I forgot to mention that I've also activated Google button and I want to authorize Microsoft button for certain users only and authorize every user to use Google button.
When I `var_dump` the`$response` array, I cannot find any variable that helps to distinguish witch social method has been used!

There is a way to achieve that?

**Comment by nikosdion** [comment]
It's not really possible to provide this kind of granularity without introducing an arbitrary variable which _MIGHT_ break a future Joomla version and/or core or third party plugins handling login events.

The best you can probably do is check what is the current URL. Both methods use an OAuth2 callback URL _but_ it's different for each login plugin.

**Comment by ariouche** [comment]
OK thanks, I will use the `$_SERVER["REQUEST_URI"]` and parse it.
Last thing, as you mentioned earlier, even if I return `false` into the `function onUserLogin` the user is authentificated, the login is not rejected.

**Comment by nikosdion** [comment]
> OK thanks, I will use the $_SERVER["REQUEST_URI"] and parse it.

It's way easier using Joomla's `\Joomla\CMS\Uri\Uri::getInstance()` to get a Joomla URI object which has the current URL pre-parsed for you. 😉

>  Last thing, as you mentioned earlier, even if I return false into the function onUserLogin the user is authentificated, the login is not rejected.

You can always do it the very hard way, same as I do in Admin Tools when I need to deny login to a user:

```php
// Get the Joomla user object, if you have not done so already.
$joomlaUser = \Joomla\CMS\Factory::getUser(\Joomla\CMS\User\UserHelper::getUserId($user['username']));
// Get the application object (assuming you have not defined protected $app in your plugin class).
$app = \Joomla\CMS\Factory::getApplication();
// Log the user out. This handles the Joomla side of logging a user out.
$app->logout($joomlaUser, $options);
// Destroy the user session. This handles the PHP side of logging a user out.
$app->getSession()->close();
// Show the Joomla error page with a custom message on why logging in failed.
throw new Exception('Your message here', 403);
```
