### ISSUE TITLE
Please: let Social Login inherit from Login module redirect urls, it makes difference...

### ISSUE THREAD

**Issue by morphinestyle** [akeeba/sociallogin#97]
Hello,
please: let Social Login to inherit **URL redirect after access**, **URL redirect after logout**, etc. from Standard Joomla Login module in which SL appends.

It can make huge difference in case of many "public" users.

Great exension.

**Comment by nikosdion** [comment]
The only supported version for feature requests is that for Joomla 4 so I will assume that this is what we are talking about.

> URL redirect after access

You mean after login. It already does from Joomla's login module ever since it was first released for Joomla 4 a year and a half ago. It does that for Joomla's login page (which uses the com_user core component) [since September](https://github.com/akeeba/sociallogin/commit/f8f108f4056cf2bf369c9a16bf800f7890dedf62).

> URL redirect after logout

You don't log out of your site with SocialLogin. That's still handled by Joomla.

As a result, you are asking for something already implemented and released. I am closing this issue as invalid.
